# config/application.yml

AWS_ACCESS_KEY: "Your-access-key"
AWS_SECRET_KEY: "Your-secret-key"
AWS_BUCKET:     "Your-bucket"
AWS_REGION:     "us-east-1"

SECRET_KEY: 'sk_test_kkFBX1hAaF2WX9VllunZJQik00vXyrkYWX'
PUBLISHABLE_KEY: 'pk_test_T85Wksgxc0LDxes49FadbAJv00R4NLiyBQ'